name: Update Tree JSON

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate tree.json
        run: |
          mkdir -p json
          echo "Generating tree..."

          find sharedfiles -type f | jq -R -s '
            split("\n")
            | map(select(length > 0))
            | map({
                type: "file",
                name: split("/") | last,
                path: .
              })
          ' > json/tree.json

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add json/tree.json
          git commit -m "auto update tree.json" || exit 0
          git push